common/urls.py
from django.urls import path

from . import views
app_name = 'common'

urlpatterns = [
  path('', views.index, name='index'),
  path('home/', views.home, name='home'),
  path('profile/', views.view_profile, name='profile'),
  path('top_bar/', views.top_bar, name='top_bar'),
  path('sidebar/', views.sidebar, name='sidebar')
]

crm_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('common.urls')),
    path('', include('project_management.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_management/urls.py
from django.urls import path, include

from . import views

app_name = 'project_management'



urlpatterns = [

 path('project/', views.project, name = 'project'),
 path('project_detail', views.project_detail, name='project_detail'),
 path('clients', views.clients, name='clients'),
 path('client', views.client, name='client'),
 path('contractors', views.contractors, name='contractors'),
 path('contractor', views.contractor, name='contractor'),
 path('reports', views.reports, name='reports'),
 path('report', views.report, name='report'),
 path('sites', views.sites, name='sites'),
 path('site', views.site, name='site'),
 path('teams', views.teams, name='teams'),
 path('team', views.team, name='team'),

]

users/urls.py
from django.urls import path, include


app_name = 'users'
from . import views

urlpatterns = [
 path('', include('django.contrib.auth.urls')),
 path('register/', views.register, name='register'),

]

common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='images/', default='purpose.jpg', null=True, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    phone_number = models.CharField(max_length=12, blank=True)
    birth_date = models.DateTimeField(null=True, blank=True)
    location = models.CharField(max_length=30, blank=True)
    entry_designation = models.CharField(max_length=255, blank=True, null=True)
    entry_scale = models.CharField(max_length=255, blank=True, null=True)
    position = models.CharField(max_length=100, blank=True, null=True)




@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

hr/models.py
from django.db import models

# Create your models here.

project_management/models.py
from django.db import models
from common.models import Profile
# Create your models here.

users/models.py
from django.db import models

# Create your models here.

common/forms.py
from django.forms import ModelForm
from .models import *

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=30, required=True, help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

common/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'common/index.html')

@login_required
def home(request):
    return render(request, 'common/home.html')

@login_required
def view_profile(request):
    return render(request, 'common/profile.html')


def top_bar(request):
    return render(request, 'common/top_bar.html')

def sidebar(request):
    return render(request, 'common/sidebar.html')

hr/views.py
from django.shortcuts import render

# Create your views here.

project_management/views.py
from django.shortcuts import render
from .models import *
# Create your views here.
def project(request):
    return render(request, 'project_management/project.html')



def project_detail(request):
    return render(request, 'project_management/project_detail.html')


def client(request):
    return render(request, 'project_management/client.html')


def clients(request):
    return render(request, 'project_management/clients.html')



def contractors(request):
    return render(request, 'project_management/contractors.html')



def contractor(request):
    return render(request, 'project_management/contractor.html')


def sites(request):
    return render(request, 'project_management/sites.html')


def site(request):
    return render(request, 'project_management/site.html')


def teams(request):
    return render(request, 'project_management/teams.html')

def team(request):
    return render(request, 'project_management/team.html')



def reports(request):
    return render(request, 'project_management/reports.html')


def report(request):
    return render(request, 'project_management/report.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
from .forms import SignUpForm


def register(request):
    if request.method != 'POST':
        form = SignUpForm()
    else:
        form = SignUpForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('common:home')

    context = {'form': form}
    return render(request, 'registration/register.html', context)


def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        if form.is_valid():
            login(request, user)
            redirect('common:home')
    else:
        note = "Ivalid Username or Password"
        redirect('users:login')
    return render(request, 'registeration/login.html', {note:'note'})

common/templates/common/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>CRM - Home</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-warning">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block">
                <img src="{% static 'img/django-crm-home.png' %}" class="rounded" alt="Cinque Terre">
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome To Django CRM!</h1>
                  </div>
                  <a href="{% url 'users:register' %}" class="btn btn-danger btn-block btn-lg">Register / Sign Up</a>
                  <br>
                  <a href="{% url 'users:login' %}" class="btn btn-primary btn-block btn-lg">Login</a>
                  <br>
                  <a href="#" class="btn btn-success btn-block btn-lg">Forgot Password</a>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="#">Contact</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="#">niel.sharma805@gmail.com</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

common/templates/common/profile.html
{% extends 'common/base.html' %}
 {% load static %}

 {% load crispy_forms_tags %}

 {% block content %}
     <!-- Begin Page Content -->
     <div class="container-fluid">

         <!-- Page Heading -->
         <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
         <h1 class="h3 mb-0 text-gray-800">Profile</h1>
         </div>

         {% if messages %}
           {% for message in messages %}
           <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
           {% endfor %}
         {% endif %}

         <!-- Main Content Here -->
         <div class="row">
           <div class="col-lg-2"></div>
           <div class="col-lg-3 my-5">
             <img src="{{user.profile.avatar.url}}" class="rounded float-right" height="300px" width="300px">
           </div>
           <div class="card o-hidden border-0 shadow-lg my-5 col-lg-5">
             <div class="card-body">
                 <h2>{{user.first_name}} {{user.last_name}}</h2>
                 <p><strong>Email: </strong> {{user.username}} </p>
                 <p><strong>Email: </strong> {{user.email}} </p>
                 <p><strong>Bio: </strong> {{user.profile.bio}} </p>
                 <p><strong>Phone Number: </strong> {{user.profile.phone_number}} </p>
                 <p><strong>DOB: </strong> {{user.profile.birth_date}} </p>
                 <a href="#" class="btn btn-sm btn-primary shadow-sm">Update Profile</a>
             </div>
           </div>
         </div>



     </div>
     <!-- /.container-fluid -->
 {% endblock content %}

common/templates/common/top_bar.html
{% extends 'common/sidebar.html' %}
{% load static %}

{% block content %}

<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
      <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Search -->
            <form
                class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                        aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-search fa-fw"></i>
                    </a>

                    <div class="topbar-divider d-none d-sm-block"></div>

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                            <img class="img-profile rounded-circle"
                                src="img/undraw_profile.svg">
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                            aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                Profile
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                Settings
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                Activity Log
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>

                </ul>

            </nav>

{% endblock content %}

project_management/templates/project_management/client.html
{% extends 'common/sidebar.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row">

      <!-- Earnings (Monthly) Card Example -->
    <a href="{%  url 'project_management:project' %}"></a>
      <div class="col-xl-3 col-md-6 mb-4">

          <div class="card border-left-primary shadow h-100 py-2">
              <div class="card-body">
                  <div class="row no-gutters align-items-center">
                      <div class="col mr-2">

                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                              <a href="{% url 'project_management:project' %}">PROJECTS (Monthly)</a></div>
                          <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>

                      </div>

                      <div class="col-auto">
                          <i class="fas fa-calendar fa-2x text-gray-300"></i>
                      </div>
                  </div>
              </div>
          </div>

      </div>


      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-left-success shadow h-100 py-2">
              <div class="card-body">
                  <div class="row no-gutters align-items-center">
                      <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                              ClIENT (details)</div>
                          <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
                      </div>
                      <div class="col-auto">
                          <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                      </div>
                  </div>
              </div>
          </div>
      </div>

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-left-info shadow h-100 py-2">
              <div class="card-body">
                  <div class="row no-gutters align-items-center">
                      <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
                          </div>
                          <div class="row no-gutters align-items-center">
                              <div class="col-auto">
                                  <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                              </div>
                              <div class="col">
                                  <div class="progress progress-sm mr-2">
                                      <div class="progress-bar bg-info" role="progressbar"
                                          style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                          aria-valuemax="100"></div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="col-auto">
                          <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                      </div>
                  </div>
              </div>
          </div>
      </div>

      <!-- Pending Requests Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-left-warning shadow h-100 py-2">
              <div class="card-body">
                  <div class="row no-gutters align-items-center">
                      <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                              Pending Requests</div>
                          <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                      </div>
                      <div class="col-auto">
                          <i class="fas fa-comments fa-2x text-gray-300"></i>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
</div>


{% endblock content %}

project_management/templates/project_management/clients.html
{% extends 'common/sidebar.html' %}
{% load static %}
{% block content %}



<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
        For more information about DataTables, please visit the <a target="_blank"
            href="https://datatables.net">official DataTables documentation</a>.</p>



    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                        </tr>
                    </tfoot>
                    <tbody>

                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>


                        <tr>
                            <td>Donna Snider</td>
                            <td>Customer Support</td>
                            <td>New York</td>
                            <td>27</td>
                            <td>2011/01/25</td>
                            <td>$112,000</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->




{% endblock content %}

project_management/templates/project_management/contractors.html
{% extends 'common/base.html' %}
{% load static %}
{% block content %}






<div class="container-fluid">

  <h1 class="h3 mb-2 text-gray-800">Contractors- 200</h1>
  <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
      For more information about DataTables, please visit the <a target="_blank"
          href="https://datatables.net">official DataTables documentation</a>.</p>

 <hr class="featurette-divider">

  <div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-black  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Active Contractors</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">800</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-black  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">InActive Contractors</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">400</h3>
			  	</div>
			</div>
		</div>
	</div>

  </div>



    <!-- Page Heading -->

   <hr class="featurette-divider">

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">All Contractors</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                        </tr>
                    </tfoot>
                    <tbody>

                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>


                        <tr>
                            <td>Donna Snider</td>
                            <td>Customer Support</td>
                            <td>New York</td>
                            <td>27</td>
                            <td>2011/01/25</td>
                            <td>$112,000</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->




{% endblock content %}

project_management/templates/project_management/project.html
{% extends 'common/base.html' %}
{% load static %}
{% block content %}






<div class="container-fluid">

  <h1 class="h3 mb-2 text-gray-800">Projects- 1200</h1>
  <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
      For more information about DataTables, please visit the <a target="_blank"
          href="https://datatables.net">official DataTables documentation</a>.</p>

 <hr class="featurette-divider">

  <div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-black  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Projects Active</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">800</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-black  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Projects InActive</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">400</h3>
			  	</div>
			</div>
		</div>
	</div>

  </div>



    <!-- Page Heading -->

   <hr class="featurette-divider">

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">All Projects</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                        </tr>
                    </tfoot>
                    <tbody>

                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>


                        <tr>
                            <td>Donna Snider</td>
                            <td>Customer Support</td>
                            <td>New York</td>
                            <td>27</td>
                            <td>2011/01/25</td>
                            <td>$112,000</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->




{% endblock content %}

project_management/templates/project_management/project_detail.html
{% extends 'common/base.html' %}

{% load static %}

{% block content %}



<!-- Begin Page Content -->
<div class="container-fluid">


    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Project description</h1>



    <p class="lead">Bootstrap's default utility classes can be found on the official <a
            href="https://getbootstrap.com/docs">Bootstrap Documentation</a> page. The custom utilities
        below were created to extend this theme past the default utility classes built into Bootstrap's
        framework.</p><!-- Default dropup button -->
<div class="btn-group dropup">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropup
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Report issue</a>
    <a class="dropdown-item" href="#">Request</a>
    <a class="dropdown-item" href="#">Warning</a>
    <!-- Dropdown menu links -->
  </div>
</div>


<hr class="featurette-divider">
    <!-- Content Row -->
    <h1 class="h3 mb-1 text-gray-800">Project Details</h1>

      <dl class="row">
        <dt class="col-sm-3">Description lists</dt>
        <dd class="col-sm-9">A description list is perfect for defining terms.</dd>

        <dt class="col-sm-3">Euismod</dt>
        <dd class="col-sm-9">
          <p>Vestibulum id ligula porta felis euismod semper eget lacinia odio sem nec elit.</p>
          <p>Donec id elit non mi porta gravida at eget metus.</p>
        </dd>

        <dt class="col-sm-3">Malesuada porta</dt>
        <dd class="col-sm-9">Etiam porta sem malesuada magna mollis euismod.</dd>

        <dt class="col-sm-3 text-truncate">Truncated term is truncated</dt>
        <dd class="col-sm-9">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</dd>

        <dt class="col-sm-3">Nesting</dt>
        <dd class="col-sm-9">
          <dl class="row">
            <dt class="col-sm-4">Nested definition list</dt>
            <dd class="col-sm-8">Aenean posuere, tortor sed cursus feugiat, nunc augue blandit nunc.</dd>
          </dl>
        </dd>
       </dl>


<hr class="featurette-divider">

      <table class="table table-bordered">
<thead><h1 class="h3 mb-1 text-gray-800">Project Team</h1><button type="button" class="btn btn-primary btn-sm">Edit</button>

<tr>
<th scope="col">#</th>
<th scope="col">First</th>
<th scope="col">Last</th>
<th scope="col">Handle</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">1</th>
<td>Mark</td>
<td>Otto</td>
<td>@mdo</td>
</tr>
<tr>
<th scope="row">2</th>
<td>Jacob</td>
<td>Thornton</td>
<td>@fat</td>
</tr>
<tr>
<th scope="row">3</th>
<td colspan="2">Larry the Bird</td>
<td>@twitter</td>
</tr>
</tbody>
</table>

<hr class="featurette-divider">

  <h1 class="h3 mb-1 text-gray-800">Previous Reports</h1>

  <ul class="list-group">
  <li class="list-group-item active">Cras justo odio</li>
  <li class="list-group-item">Dapibus ac facilisis in</li>
  <li class="list-group-item">Morbi leo risus</li>
  <li class="list-group-item">Porta ac consectetur ac</li>
  <li class="list-group-item">Show all the reports</li>
</ul>

<hr class="featurette-divider">


<div class="card text-center" style="width: 200px:">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title">Payments</h5>
    <p class="card-text">All payments invoices made till now for this project.</p>
    <a href="#" class="btn btn-primary">Click here</a>
  </div>
  <div class="card-footer text-muted">
    Updated 2 days ago
  </div>
</div>

</div>









{% endblock content %}